---
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.145.49
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'