version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce:latest
    network_mode: host
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data