---
# tasks file for vector
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: "0644"
  notify: Start vector service
- name: Install vector packages
  become: true
  ansible.builtin.dnf:
    name:
      - vector-{{ vector_version }}.rpm
    disable_gpg_check: true
- name: Flush handlers to restart vector
  ansible.builtin.meta: flush_handlers
- name: Configure Vector | ensure that directory exists
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0755"
- name: Configure Vector | Template config
  ansible.builtin.template:
    src: "templates/vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"
