---
all:
  hosts:
    prod-vm-jenkins-master-1:
      ansible_host: 89.169.152.21
    prod-vm-jenkins-agent-1:
      ansible_host: 89.169.134.132
    prod-vm-jenkins-agent-2:
      ansible_host: 51.250.1.174
  children:
    jenkins_master:
      hosts:
        prod-vm-jenkins-master-1:
    jenkins_agent:
      hosts:
        prod-vm-jenkins-agent-1:
        prod-vm-jenkins-agent-2:

  vars:
    ansible_connection_type: paramiko
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'