apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool:latest
      command:
        - /bin/sh
        - -c
        - >
          while true;
          do echo "$(date) - multitool";
          sleep 10;
          done;