apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31180