- name: Install Docker CE
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes

- name: Install prerequisites for docker-compose
  become: true
  apt:
    name: ['python3-pip', 'python3-setuptools', 'virtualenv']

- name: Install docker-compose
  become: true
  pip:
    name: docker-compose

- name: Update pip
  become: true
  pip:
    executable: pip3
    name: pip
    extra_args: --upgrade

- name: Create docker group
  become: true
  group:
    name: docker
    state: present
