apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-service
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := $.Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.port }}
      nodePort: {{ $port.nodePort }}
      protocol: {{ $port.protocol | upper }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- include "my-chart.selectorLabels" . | nindent 4 }}
