---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 89.169.146.110
      ansible_user: admin
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      become: true
      

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.53.152
      ansible_user: admin
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      become: true

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 89.169.128.56
      ansible_user: admin
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      become: true


local:
  hosts:
    localhost:
      ansible_connection: local
