---
all:
  hosts:
    prod-vm-cicd-1:
      ansible_host: 89.169.129.3
    prod-vm-cicd-2:
      ansible_host: 89.169.140.148
  children:
    sonarqube:
      hosts:
        prod-vm-cicd-1:
    nexus:
      hosts:
        prod-vm-cicd-2:
    postgres:
      hosts:
        prod-vm-cicd-1:

  vars:
    ansible_connection_type: paramiko
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'