---
- src: https://git@github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: https://git@github.com/mea2k/ansible-role-vector
  scm: git
  version: "1.0.0"
  name: vector

- src: https://git@github.com/mea2k/ansible-role-lighthouse
  scm: git
  version: "1.0.0"
  name: lighthouse


